export const WS_CONNECTION_START_USER = 'WS_CONNECTION_START_USER';
export const WS_CONNECTION_SUCCESS_USER = 'WS_CONNECTION_SUCCESS_USER';
export const WS_CONNECTION_ERROR_USER = 'WS_CONNECTION_ERROR_USER';
export const WS_CONNECTION_CLOSED_USER = 'WS_CONNECTION_CLOSED_USER';
export const WS_GET_MESSAGE_USER = 'WS_GET_MESSAGE_USER';
export const WS_CLOSE_CONNECTION_USER = 'WS_CLOSE_CONNECTION_USER';